### ISSUE TITLE
Table-related infinite loop triggered in versions >= 1.0.2

### ISSUE THREAD

**Issue by bsmelo** [danfickle/openhtmltopdf#615] opened 2020-12-03 21:47 UTC
Hello!

We found an infinite loop being triggered using openhtmltopdf 1.0.4. Actually, after some tests, we found our code succeeds using openhtmltopdf 1.0.1, but from 1.0.2 onwards it enters the infinite loop. The smallest input we could construct was:
```html
<table style="float:left; margin:1px;">
   <tr></tr>
</table>
<p>NOME</p>
```

Since we have a preprocessing phase using jsoup, the actual input to openhtmltopdf is:
```html
<html>
 <head>
  <style>  body { word-wrap: break-word } table { width: 100% }  </style>
 </head>
 <body>
  <table style="float:left; margin:1px;"> 
   <tbody>
    <tr></tr> 
   </tbody>
  </table> 
  <p>NOME</p>
 </body>
</html>
```

We still couldn't figure out what exactly causes the program to loop, but if we remove any piece of the above input (e.g.: `float:left;` or even `<p>NOME</p>`) it doesn't loop at all. The following code can be used to reproduce the issue:

```java
            ByteArrayOutputStream streamPdfa = new ByteArrayOutputStream();
            PdfRendererBuilder geradorPdf = new PdfRendererBuilder();
            htmlConteudoAjustado = "<THE INPUT ABOVE>";
            
            geradorPdf.withProducer("Nome Produtor");
            geradorPdf.useFastMode();
            geradorPdf.withHtmlContent(htmlConteudoAjustado, "");
            geradorPdf.toStream(streamPdfa);
            geradorPdf.run();
```

We're introducing a local, pre-processing fix, while also debugging and trying to figure out if we can contribute a fix at the openhtmltopdf side.

Thanks for the lib!

**Comment by syjer** [comment] 2020-12-04 13:53
hi @bsmelo I can confirm the issue.

Looks like a problem inside the Layout algorithm for Inline text.

(More specifically it seems to start from `InlineBoxing.layoutText()` )

**Comment by syjer** [comment] 2020-12-04 14:01
It seems to remain stuck inside this loop:

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/InlineBoxing.java#L165

**Comment by syjer** [comment] 2020-12-04 14:03
the call at https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/InlineBoxing.java#L198
 always return "LINE_FINISHED".

**Comment by syjer** [comment] 2020-12-04 14:09
even simpler reproducer:

```html
<html>
<head>
</head>
<body style="word-wrap:break-word">
<div style="width:100%;float:left;margin:1px"><span></span></div>
<p>a</p>
</body>
</html>
```

To be noted: margin:1px is important, the empty span is also important.

**Comment by danfickle** [comment] 2020-12-04 14:16
Thanks both, strongly suspect it is hitting continue on L202 in endless loop. Will further debug now.

https://github.com/danfickle/openhtmltopdf/blob/73731543655c75604837a3725883b513938cc33b/openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/InlineBoxing.java#L202

**Comment by LAlves91** [comment] 2020-12-04 14:38
Greetings @danfickle!

If you guys find the solution to this issue, will it be released in the next planned version or do you think it would be possible to release something like a "bugfix" version?

Cheers and thank you for the great work!

**Comment by danfickle** [comment] 2020-12-04 15:28
The core problem is that float clearing is not working. If you take out the `break-word` style, one can see that the paragraph is still incorrectly on the right side of the screen.

This then feeds into a too fragile test (my fault) in the `break-word` breaker:
````java
                    if (totalWidth == 0 &&
                        avail == lineWidth) {
                        // We are at the start of the line but could not fit a single character!
                        totalWidth += context.getWidth();
                        break LOOP;
                    } else {
                        // We may be at the end of the line, so pick up at next line.
                        context.setEnd(savedEnd);
                        break LOOP;
                    }
````
Here, `avail == lineWidth` is never true as the float clearance failed, leading to an endless loop.

Anyway, got to continue tomorrow...

Of course, I'll do a release once this serious issue is fixed (perhaps also #614 regression).

**Closed as completed** 2020-12-18 11:59 UTC

**Comment by LAlves91** [comment] 2020-12-18 15:08
Hey @danfickle! Firstly, I wanna thank you a lot for working on this issue!

So, I know this one is closed already, but I wanted to use the space to make a suggestion: do you guys think it would be possible to add some kind of 'Developer Guide' to the wiki?

I'm speaking for myself, but I really wanted to help solving this issue, but the architecture is really complex (totally fitting to the **extremelly complex** problem it solves, of course), so it's kind of intimidating to start. I believe an architecture documentation (even only a few diagrams showing layers and flow) would help bringing more contributions!

Thank you!

**Comment by syjer** [comment] 2020-12-20 16:44
Hi @LAlves91 , 

> do you guys think it would be possible to add some kind of 'Developer Guide' to the wiki?

Good idea. 

> so it's kind of intimidating to start.

It's a big project, but you can identify a few logical "modules" and phases. Generally, for developing, I add a test and follow with the debugger the various points that I'm interested with.
