### ISSUE TITLE
Getting a nullptr exception, reproduction case included

### ISSUE THREAD

**Issue by ThomHurks** [danfickle/openhtmltopdf#594] opened 2020-11-08 20:43 UTC
Hi!

First of all, it's been great using your library. Good work!

I noticed that with certain content (part of the content I include in the HTML is generated) I'm getting a crash when the PDF is generated. I managed to reduce the problem to a case that is pretty minimal I think;
https://github.com/ThomHurks/openhtmltopdfcrash

The nullpointer exception happens when OpenHtmlToPdf calls ```org.apache.pdfbox.cos.COSArray.add(COSArray.java:62)```

If you need any help in figuring out the problem, please let me know!

Full stacktrace:
```
com.openhtmltopdf.general INFO:: Using fast-mode renderer. Prepare to fly.


java.lang.NullPointerException
	at org.apache.pdfbox.cos.COSArray.add(COSArray.java:62)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishNumberTree(PdfBoxAccessibilityHelper.java:847)
	at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.finish(PdfBoxFastOutputDevice.java:911)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:670)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:559)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:477)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:414)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:396)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:42)
	at com.example.openhtmltopdfcrash.OpenHtmlToPdfCrash.reproduce(OpenHtmlToPdfCrash.java:34)
```

**Comment by syjer** [comment] 2020-11-12 10:22
hi @ThomHurks , thank you for providing a minimal test case.

It seems to be the same issue as https://github.com/danfickle/openhtmltopdf/issues/527  and https://github.com/danfickle/openhtmltopdf/issues/401

**Comment by danfickle** [comment] 2020-11-13 16:12
@ThomHurks, @syjer 

Thanks for the test case! After much debugging (at least six hours!), it turns out the core problem is that content (the last table row specifically) is being repeated where it shouldn't be in the page margins (not visibly) (and the accessibility code doesn't act well on this bug). This is similar to #458.

I was able to finally reproduce in a smaller sample and I have committed this as a (failing currently) test case. I will continue working on this to fix it.

Thanks again.

**Comment by ThomHurks** [comment] 2020-11-14 18:00
Thanks a lot for the help, @danfickle! That sounds like a die-hard debugging session. Great work you're doing here 👍

**Comment by danfickle** [comment] 2020-11-27 11:48
Hi @ThomHurks,

I have added PR #610 that fixes this problem. However, I just need to create some more tests before merging and then I can do a release finally.

**Closed as completed** 2020-11-28 10:30 UTC
Labels: bug, has failing test

**Comment by ThomHurks** [comment] 2020-11-30 08:01
@danfickle Thanks a lot! Amazing job 👌
