### ISSUE TITLE
When I give multiple span tags for styling converting fails.

### ISSUE THREAD

**Issue by Holbrooki** [danfickle/openhtmltopdf#671] opened 2021-03-19 09:17 UTC
```HTML
<p>invalid format</p>
  <span style="font-family:'Courier Prime'">
      <span style="color:yellow">
             <span style="font-size:36pt">
                 Hello World!
            </span>
     </span> 
  </span>
 
<p>working format</p>
  <span style="font-family:'Courier Prime';color:yellow;font-size:36pt">Hello World!</span>
```

![kép](https://user-images.githubusercontent.com/14187952/111757760-f49a6680-889b-11eb-8dd0-f9815156eaf8.png)

**Comment by danfickle** [comment] 2021-03-19 09:25
I just tried this (using monospace instead of `Courier Prime` and it worked for both. I'm using version 1.0.6.

````html
<body>

<p>invalid format</p>
  <span style="font-family:monospace;">
      <span style="color:yellow">
             <span style="font-size:36pt">
                 Hello World!
            </span>
     </span> 
  </span>
 
<p>working format</p>
  <span style="font-family:monospace;color:yellow;font-size:36pt">Hello World!</span>

</body>
````

Are you sure you don't have an overriding `font-family` for `span` in your stylesheet?

**Comment by Holbrooki** [comment] 2021-03-19 09:56
I have a PdfRendererBuilder bean for configuring and loading fonts from a folder which can be used by frontend. This is all my html, font-family is not overridden. I'm not familiar with fonts, how do I handle getting the exact font-names in styling?

**Comment by danfickle** [comment] 2021-03-22 11:10
You can use the name as used when you added the font with one of the `useFont` methods:
````java
builder.useFont(new File("..."), "font-family-here");
````

However, it is strange that it is working in some places and not others.

**Comment by danfickle** [comment] 2021-09-10 12:10
Closing now as could not reproduce. However, please reopen if required.

**Closed as completed by danfickle** 2021-09-10 12:10 UTC
