### ISSUE TITLE
Fine lines appearing between table cells

### ISSUE THREAD

**Issue by ralleman** [danfickle/openhtmltopdf#291] opened 2018-11-09 23:32 UTC
Even with borders completely collapsed, there is still a fine line between the cells of tables when there is some background-color on the td, but not the tr or table. These lines are always the same width no matter how much I zoom the PDF. Setting the border-color to the same as the td background-color doesn't eliminate it.
<img width="606" alt="fine-lines" src="https://user-images.githubusercontent.com/5635170/48293562-553a5d00-e4b2-11e8-881a-8697140e262c.png">

**Comment by ralleman** [comment] 2018-11-09 23:34
<img width="984" alt="fine-lines2" src="https://user-images.githubusercontent.com/5635170/48293636-af3b2280-e4b2-11e8-8498-86e6e5aa1f74.png">

**Comment by danfickle** [comment] 2018-11-11 04:31
Hi @ralleman,

Thanks for the visual mock up highlighting the problem.

I've added a test that confirms this issue (and increases the chance that it will be fixed). I had a look in the generated PDF and on first inspection it looks correct (below). I suspect that the cause might be that PDF paths are not inclusive, but I'll have to look in the spec to confirm (and figure out what this means in the context of floating point units).

````
42 799.875 m
42 783.375 l
118.5 783.375 l
118.5 799.875 l
h
f
118.5 799.875 m
118.5 783.375 l
195 783.375 l
195 799.875 l
h
f
195 799.875 m
195 783.375 l
271.5 783.375 l
271.5 799.875 l
h
f
42 783.375 m
42 766.875 l
118.5 766.875 l
118.5 783.375 l
h
f
118.5 783.375 m
118.5 766.875 l
195 766.875 l
195 783.375 l
h
f
195 783.375 m
195 766.875 l
271.5 766.875 l
271.5 783.375 l
h
f
````

**Closed as completed** 2021-09-12 05:19 UTC
Labels: has failing test
