### ISSUE TITLE
Using separate CSS-file to style different html-inputs

### ISSUE THREAD

**Issue by steam0** [danfickle/openhtmltopdf#146] opened 2017-11-06 07:09 UTC
I was wondering if it is possible to use separate CSS-files to style multiple html-documents in the same way.

For now I have had to put the styling inside every HTML-document, but that is a waste since I will have between tens and houndreds of different documents which should all conform to the same stylesheet.

Any suggestions?

**Comment by danfickle** [comment] 2017-11-07 05:13
Hi @steam0 

You can use the standard ```link``` in the ```head``` section:
````html
<html>
<head>
<link rel="stylesheet" href="style.css"/>
</head>
<body>
<div>
Hello World!
</div>
</body>
</html>
````
You can also ````@import```` from a CSS file. Remember that you may need to provide a base directory if using relative file paths to link to your css.

**Comment by steam0** [comment] 2017-11-07 06:17
How do I provide a base directory? Any basic example?

**Comment by silentsnooc** [comment] 2019-09-16 16:48
Same question: How to provide a base directory?

**Comment by ghost** [comment] 2019-09-16 16:53
Same question: How to set a base directory? I am getting:

```
com.openhtmltopdf.load WARNING:: Unable to load CSS from styles.css
```

**Comment by geekonthepc** [comment] 2019-09-19 16:09
Just been working on this today.

Use baseUrl here to define a base URL.
`builder.withHtmlContent(sourceHtml, baseUrl);`

**Comment by srinivasthutika** [comment] 2020-03-10 13:33
when i use link as below (Using 1.0.2) in html
`<link rel="stylesheet" type="text/css" href="style.css"/>`



I am getting following exception (Any help would be appreciated.)
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
**com.openhtmltopdf.load INFO:: The element type "link" must be terminated by the matching end-tag "</link>".**
**ERROR:  'The element type "link" must be terminated by the matching end-tag "</link>".'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 4; The element type "link" must be terminated by the matching end-tag "</link>".**
com.openhtmltopdf.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 4; The element type "link" must be terminated by the matching end-tag "</link>".
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:274)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
	at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:81)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentFromStringP(PdfBoxRenderer.java:293)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:235)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:63)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:39)
	at GenerateHtmlToPDF.generateHtmlToPDF(GenerateHtmlToPDF.java:53)
	at GenerateHtmlToPDF.main(GenerateHtmlToPDF.java:21)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 4; The element type "link" must be terminated by the matching end-tag "</link>".

**Comment by srinivasthutika** [comment] 2020-03-10 13:42
I am getting following exception if i use it as you mentioned. any help would be appreciated.
**com.openhtmltopdf.load INFO:: The element type "link" must be terminated by the matching end-tag "".
ERROR: 'The element type "link" must be terminated by the matching end-tag "".'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 4; The element type "link" must be terminated by the matching end-tag "".**

**Comment by srinivasthutika** [comment] 2020-03-10 19:51
> Just been working on this today.
> 
> Use baseUrl here to define a base URL.
> `builder.withHtmlContent(sourceHtml, baseUrl);`

what is baseURL here means ??

**Comment by danfickle** [comment] 2020-03-16 12:30
This library expects valid XML by default. This means all tags need a closing tag or be self-closing:
````xml
<link href="..." />
<link href="..."></link>
````
Either of the above are fine. If you have HTML that is not valid XML, you can convert it. The recommended way to do this is use Jsoup library to parse and convert. However, this is not working perfectly due to #445. It will be fixed in the next release.

````java
var jsoupDoc = Jsoup.parse(html);
var w3cDoc = new W3CDom().fromJsoup(jsoupDoc);

builder.withW3cDocument(w3cDoc, baseUrlMaybeNull);
````

The base url may be null, if not the path is used as the base for resolving relative resources such as images, css stylesheets, etc. It must be a url such as `file:///home/dan/some-path/` or `http://localhost:8080/some/path/`.

**Comment by aleks-shbln** [comment] 2020-04-11 16:20
Using separate resources can be achieved by providing your own FSStreamFactory:
```
new PdfRendererBuilder()
    .useProtocolsStreamImplementation(new ClassPathStreamFactory(), "classpath")
    .withHtmlContent(htmlContent, "classpath:/html/")
    ...
```
Full code can be found in this [example project](https://github.com/aleks-shbln/separate-resources-example)

**Closed as completed** 2021-01-03 13:14 UTC

**Comment by daniel-shuy** [comment] 2024-01-23 10:16
> Using separate resources can be achieved by providing your own FSStreamFactory:
> 
> ```
> new PdfRendererBuilder()
>     .useProtocolsStreamImplementation(new ClassPathStreamFactory(), "classpath")
>     .withHtmlContent(htmlContent, "classpath:/html/")
>     ...
> ```
> 
> Full code can be found in this [example project](https://github.com/aleks-shbln/separate-resources-example)

Would be great if [ClassPathStreamFactory](https://github.com/aleks-shbln/separate-resources-example/blob/master/src/main/java/io/ashabalin/ohtp/separateresources/pdf/ClassPathStreamFactory.java) could be added to this library!

**Comment by zacharysiegel** [comment] 2024-01-23 18:02
> Would be great if [ClassPathStreamFactory](https://github.com/aleks-shbln/separate-resources-example/blob/master/src/main/java/io/ashabalin/ohtp/separateresources/pdf/ClassPathStreamFactory.java) could be added to this library!

@daniel-shuy 
This looks both useful and easy (the best kind of feature). Could you open an issue on [this project](https://github.com/openhtmltopdf/openhtmltopdf). Unfortunately, this repository is no longer maintained.

edit: Just realized we haven't enabled Issues on the other repo yet. Working on that. We're only recently transitioning to developing on the other project. see #921

**Comment by daniel-shuy** [comment] 2024-01-24 12:39
@siegelzc didn't know this repository is no longer maintained, thanks!

I'll create a PR. I just realized that its not a straight copy as the code depends on Spring Boot, but can be re-implemented in a way that doesn't depend on Spring Boot

**Comment by daniel-shuy** [comment] 2024-01-24 14:07
@siegelzc created a PR at openhtmltopdf#3
