### ISSUE TITLE
Release without "RC" in version number

### ISSUE THREAD

**Issue by tahoell** [danfickle/openhtmltopdf#367] opened 2019-07-10 11:16 UTC
Hi everybody,

we would like to use openhtmltopdf in our project. Unfortunatly our customer only allow us to use libraries, that don't contain "RC" in the version number. Would it be possibly to make a release without "RC" in a version number, for example "0.0.1"? It would be even better if the version number did not contain "0" in the second position, such as "0.1.0". 
Would it be possible? 
Thank you!

**Comment by ieugen** [comment] 2019-07-10 14:54
Hi @tahoell 

I'm not a developer with Openhtmltopdf so I don't speak for them.
Hoever
This is an open source project. You can and should build your own releases if this does not suit you. 
You can version those however you want but that won't change the fact that this software comes with no warranties or is not considered, by the authors - feature complete = version 1.0 ready.

**Comment by tahoell** [comment] 2019-07-12 06:31
Hello @ieugen 

Thank you for the quick reply! Unfortunately for contractual reasons we can't use open source libraries that we build ourselves. 

We would still like to use the library, because it would really help us. What do developers think about this?

**Comment by danfickle** [comment] 2019-07-13 03:48
I think a v1 release for the PDF functionality is probably reasonable. It has a couple of hundred tests and I think people are using it in production. The problem is the java2d output side which has no tests and is bit rotting as we add features to the PDF side. I'm not sure what to do with this module.

Anyway, I'm inclined to do the v1 release (with a note about java2d output not meeting this standard) unless there are objections. @tahoell when do you need the release by? I'd like a week or so to get the work in replaced_sizing branch finished and merged.

**Comment by tahoell** [comment] 2019-07-13 13:41
Hi @danfickle 
That's great! One week is perfect. Thank you very much for your quick help, I really appreciate it!

**Comment by lperdigao** [comment] 2019-07-22 09:22
Hey guys! Thank you for the good work you've been doing so far. We would benefit a lot on a v1 release as well. Any update when you are able to do a release :) ?
Thanks in advance 
Luis

**Comment by danfickle** [comment] 2019-07-22 13:23
Release planned for tomorrow!

**Comment by danfickle** [comment] 2019-07-23 06:12
Version `1.0.0` has just been sent to maven central! Enjoy.

**Closed as completed by danfickle** 2019-07-23 06:12 UTC
Labels: question
