### ISSUE TITLE
getClip is being used by the fast renderer.

### ISSUE THREAD

**Issue by nullquery** [danfickle/openhtmltopdf#246] opened 2018-07-10 10:09 UTC
```
webapp 2018-07-10 12:02:53 [main] ERROR (Log4JXRLogger.java:56) - getClip MUST not be used by the fast renderer. Please consider reporting this bug.
```

Um... Consider it reported? 😀

This is on 0.0.1-RC14. Only occurs when com.openhtmltopdf.pdfboxout.PdfRendererBuilder#useFastMode() is used.

According to the documentation, I must use the fast mode:
```Please note that the fast renderer will be the only renderer at some future release so please at least test your code using the fast mode.```

HTML input:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "../schemas/xhtml1-strict.dtd">
<html>
 <head>
  <style type="text/css">
    @page
    {
      size: 793px 1122px;
      margin: 50px 55px 55px 50px;
      @top-center { content: element(header); }
      @bottom-center { content: element(footer); }
    }

    body
    {
      font-family: Arial;
      font-size: 15px;
    }
  </style>
 </head>
 <body>
  <div style="position: running(header);">
   <p>Header 1</p>
  </div>
  <div style="position: running(footer);">
   <p>Footer 1</p>
  </div>
  <p>Page 1</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 2</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 3</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 4</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 5</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <div style="position: running(header);">
   <p>Header 2</p>
  </div>
  <div style="position: running(footer);">
   <p>Footer 2</p>
  </div>
  <p>Page 6</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 7</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 8</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 9</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 10</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <div style="position: running(header);">
   <p>Header 3</p>
  </div>
  <div style="position: running(footer);">
   <p>Footer 3</p>
  </div>
  <p>Page 11</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 12</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 13</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 14</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 15</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <div style="position: running(header);">
   <p>Header 4</p>
  </div>
  <div style="position: running(footer);">
   <p>Footer 4</p>
  </div>
  <p>Page 16</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 17</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 18</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 19</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 20</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <div style="position: running(header);">
   <p>Header 5</p>
  </div>
  <div style="position: running(footer);">
   <p>Footer 5</p>
  </div>
  <p>Page 21</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 22</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 23</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 24</p>
  <div style="page-break-after: always;">
   &nbsp;
  </div>
  <p>Page 25</p>
 </body>
</html>
```

**Comment by danfickle** [comment] 2019-03-10 06:14
Thanks @nullquery,

This was caused by me forgetting the page margins! Fortunately, it is now fixed with RC18 being released.

**Closed as completed by danfickle** 2019-03-10 06:14 UTC
