### ISSUE TITLE
Getting error No Such Method Error

### ISSUE THREAD

**Issue by tiagocardoso** [danfickle/openhtmltopdf#686] opened 2021-04-05 15:14 UTC
I'm getting 

java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.setVersion(F)V
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:151) ~[openhtmltopdf-pdfbox-1.0.8.jar:?]
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:69) ~[openhtmltopdf-pdfbox-1.0.8.jar:?]
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:44) ~[openhtmltopdf-pdfbox-1.0.8.jar:?]

From code

htmlDoc = Jsoup.parse(html);
OutputStream os = new FileOutputStream(pdfFile.toString());
PdfRendererBuilder builder = new PdfRendererBuilder();
builder.useFastMode();
builder.withHtmlContent(htmlDoc.toString(),"file:///description.html");
builder.toStream(os);
builder.run();

Using only maven to build the project.

Thank you,

Tiago

**Comment by syjer** [comment] 2021-04-06 07:43
hi @tiagocardoso , the code is correct, maybe you got some issue in the imported pdfbox (wrong version caused by some override?, corrupted jar?) ?

**Comment by danfickle** [comment] 2021-09-10 12:04
Closing now. Please reopen if required.

**Closed as completed by danfickle** 2021-09-10 12:04 UTC
