### ISSUE TITLE
NullPointerException by ctrl.box.getStyle when no font is definied...

### ISSUE THREAD

**Issue by renlinch** [danfickle/openhtmltopdf#203] opened 2018-04-10 13:09 UTC
Currently i resolved this for me with this.

```
diff --git a/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java b/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java
index eb4115a..a90a877 100644
--- a/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java
+++ b/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java
@@ -318,7 +318,13 @@
             if (!(ctrl.box.getElement().getAttribute("type").equals("checkbox") ||
                   ctrl.box.getElement().getAttribute("type").equals("radio") ||
                   ctrl.box.getElement().getAttribute("type").equals("hidden"))) {
-                PDFont fnt = ((PdfBoxFSFont) _sharedContext.getFont(ctrl.box.getStyle().getFontSpecification())).getFontDescription().get(0).getFont();
+            	FontSpecification spec = ctrl.box.getStyle().getFontSpecification();
+            	PDFont fnt = null;
+            	if (spec == null) {
+            		fnt = PDType1Font.COURIER ;
+                } else {
+                	fnt = ((PdfBoxFSFont) _sharedContext.getFont(ctrl.box.getStyle().getFontSpecification())).getFontDescription().get(0).getFont();
+                }
 
                 if (!controlFonts.containsKey(fnt)) {
                     fontName = "OpenHTMLFont" + controlFonts.size();

```

But why ... don't know exactly try to add soon a failing example html and css file who i can provide to public.

**Comment by danfickle** [comment] 2018-04-10 13:40
Hi, I think this is a dupe of #183 If that's the case, you could try the
workaround mentioned there, until I develop a correct fix. Please close
this issue if you agree it is a duplicate. Thanks.

**Comment by renlinch** [comment] 2018-04-10 14:42
I was trying and removed all relative settings but it didn't work.
The thing i found was there was the getStyle().getFontSpecification() empty / null the rest was in. So i did this solution to Workaround that. And that worked well for me.

**Comment by danfickle** [comment] 2018-07-22 10:36
Closing in preference of #183

**Closed as completed by danfickle** 2018-07-22 10:36 UTC
