### ISSUE TITLE
Regression: words missing using text-align: justify in pdfbox 2.0.21

### ISSUE THREAD

**Issue by lagar84** [danfickle/openhtmltopdf#543] opened 2020-08-28 15:36 UTC
Hello,

I noticed that "open-dev-v1" upgraded PDFBOX to version 2.0.21

I was upgrading some libraries, then so give PDFBOX 2.0.21 a try too.

Unfortunately, I found a regression.

I created a reproducer to illustrate the issue:

[minimal_reproducer_missing_words.txt](https://github.com/danfickle/openhtmltopdf/files/5142897/minimal_reproducer_missing_words.txt)

Using openhtml 1.0.4 with PDFBOX 2.0.20, works:
![correct_output_v1 04_pdfbox_v2 0 20](https://user-images.githubusercontent.com/7378267/91585374-5dcf8200-e92a-11ea-8097-2c70fdd13d8d.png)

But using openhtml 1.0.4 with PDFBOX 2.0.21, not all words appear on generated PDF:
![wrong_output_v1 04_pdfbox_v2 0 21](https://user-images.githubusercontent.com/7378267/91585456-75a70600-e92a-11ea-8911-096142080977.png)

I am not sure if this issue is on openhtml or PDFBOX side, so I am describing it here in the hope that someone with proper knowledge could wheighting in.

Thanks for this great library. Hope you can continue this great work.

Best wishes,
lagar84.

**Comment by danfickle** [comment] 2020-08-29 08:37
Huge thanks to @lagar84.

It turns out that PDFBOX 2.0.21 is reporting non-breaking space as having zero width. This means that our project thinks the missing words should fit on the first line. When the text is actually output the nbsp takes width and pushes the missing words into the page margin.

I have filed issue [PDFBOX-4944: Built-in fonts are reporting nbsp char as having zero width.](https://issues.apache.org/jira/browse/PDFBOX-4944) so that the PDFBOX team can address this issue. In the meantime, I have downgraded to PDFBOX 2.0.20 and added your test to our project.

Thanks again. You can leave this issue open until we come up with a new version of PDFBOX.

**Comment by danfickle** [comment] 2020-11-02 04:08
I have confirmed this is fixed with `2.0.22-SNAPSHOT`.

**Comment by danfickle** [comment] 2021-02-18 12:47
Fixed with release of 1.0.6 and PDFBOX 2.0.22. Thanks again @lagar84.

**Closed as completed by danfickle** 2021-02-18 12:47 UTC
