### ISSUE TITLE
Issue with CSS transform: scale()

### ISSUE THREAD

**Issue by hannes123bsi** [danfickle/openhtmltopdf#642] opened 2021-01-27 16:50 UTC
Issue in multiple page documents when trying to scale a string.

I'm trying to scale the string "R E C H N U N G ".
On the first 2 pages it is printed overlapped (scaled and non-scaled)
Only on the last page it is printed correctly

You'll see it in the sample file i uploaded.

[test.html.txt](https://github.com/danfickle/openhtmltopdf/files/5881670/test.html.txt)

Thanks in advance

Hannes Müller

**Comment by danfickle** [comment] 2021-02-06 14:14
Thanks @hannes123bsi,

It turns out that transforms (scale, rotate, etc) directly on `display: inline` and `inline-block` elements are repeating the element, once transformed and once not. Indeed for `inline` elements the `transform` property should be ignored altogether.

The "good" news is that transforms work when specified directly on `display: block` elements including descendants that may be `inline`, etc.

I was able to boil down the fail-case to the following, which I have committed as a failing test:
````html
<html>
<head>
<style>
@page {
  size: 150px 100px;
  margin: 0;
}
</style>
</head>
<body>
<div><span style="transform: scale(2, 2); display: inline-block;">O N E</span></div>
</body>
</html>
````

I haven't debugged yet, so don't have a cause for this strange bug.

**Comment by MichaelF25** [comment] 2021-02-11 15:43
I've found a fix: Separate lines for the `div` Tag:

```html
<html>
<head>
<style>
@page {
  size: 150px 100px;
  margin: 0;
}
</style>
</head>
<body>
<div>
<span style="transform: scale(2, 2); display: inline-block;">O N E</span>
</div>
</body>
</html>
```

**Comment by danfickle** [comment] 2021-02-18 12:41
Thanks @MichaelF25,

I have created PR #653 with a solution. However, I'm still not sure why adding spaces around the span fixes the problem, so I'll do some more investigative work before merging.

**Closed as completed** 2021-03-01 12:06 UTC
Labels: bug, has failing test

**Comment by MichaelF25** [comment] 2021-03-22 12:30
Just did a test with v1.0.7 and it seems that the issue is not (completely) resolved. At least the sample which was provided by @hannes123bsi still renders the duplicated text on the first 2 pages (interestingly not on the last page?).
