### ISSUE TITLE
org.apache.pdfbox.cos.COSDocument  - Warning: You did not close a PDF Document

### ISSUE THREAD

**Issue by jkxyz** [danfickle/openhtmltopdf#709] opened 2021-05-27 09:48 UTC
When an exception occurs during the PDF rendering (for example within an FSStreamFactory which throws), I see the following warning log printed:

```
WARN [Finalizer] org.apache.pdfbox.cos.COSDocument  - Warning: You did not close a PDF Document
```

I'm using version 1.0.8.

I would expect the document to be closed when an error occurs. 

For now I've worked around this by providing the PDDocument and closing it in a try/finally around the call to PDFRendererBuilder#run.

**Comment by syjer** [comment] 2021-05-29 13:19
hi @jkxyz ,

you are right, the problem is due to the fact that we have the following situation:

In `PdfRendererBuilder.java`

```java
public void run() throws IOException {
  try (Closeable d = applyDiagnosticConsumer(); PdfBoxRenderer renderer = this.buildPdfRenderer(d)){
    renderer.layout();
    renderer.createPDF();
  }
}
```

it will fail during the layout() call -> thus the cleanup which is done in the context of the createPDF() call is not done (the closing of the PDDocument).

Now the fix would be to do the closing in case of failure of layout(), but we need to take in to account that we offer:

`public void createPDFWithoutClosing()` as an api.

Maybe we could save the "auto closing" option as a property of the PdfBoxRenderer.

edit: most likely, we need to do a cleanup of the builder/renderer, the API has accumulated quite a lot of cruft :D

**Closed as completed** 2021-10-02 02:52 UTC
Labels: bug
