### ISSUE TITLE
Despite that table defined with the RTL direction, the table still aligned LTR

### ISSUE THREAD

**Issue by mrbora** [danfickle/openhtmltopdf#710] opened 2021-05-28 13:02 UTC
The tables aren't rendered in the right direction. 

![צילום מסך 2021-05-28 160011](https://user-images.githubusercontent.com/8150625/119987667-f421f880-bfcd-11eb-9938-96fe25800257.png)

**Comment by danfickle** [comment] 2021-05-29 12:34
Yes, by popular request I will work on tables, especially RTL after the next release. Anyway closing this issue as a duplicate of #123.

**Closed as completed by danfickle** 2021-05-29 12:34 UTC
