### ISSUE TITLE
Table borders are partly transparent

### ISSUE THREAD

**Issue by ralleman** [danfickle/openhtmltopdf#303] opened 2018-12-06 23:57 UTC
I have two neighbouring table cells with the border set to 4px between them. Irrespective of whether I set the border on the left cell or the right cell, or on both cells, half the border width becomes transparent.

In the example below, I applied the border to both cells and you can see that there are two transparent "halves" of the border.

![image](https://user-images.githubusercontent.com/5635170/49618742-c287d200-fa0d-11e8-81c5-a76122a7c00e.png)

Another, perhaps related issue I'm finding, but I **can** work around it, is that the vertical borders of table cells don't seem to have the same size as horizontal ones using the same border-width (they're visually wider than the horizontal ones). On divs, this isn't the case. horizontal and vertical borders on divs seem visually equal.

**Comment by danfickle** [comment] 2018-12-07 03:27
Hi @ralleman,

Have you used ```border-collapse: collapse``` on the table? Also, you might run into #291 and #169.

**Comment by ralleman** [comment] 2018-12-23 11:12
Hi @danfickle,

Here are the styles on the table element:

![image](https://user-images.githubusercontent.com/5635170/50382992-30234600-0710-11e9-85a7-de36d9bcdaaf.png)

And the left cell:

![image](https://user-images.githubusercontent.com/5635170/50383002-6bbe1000-0710-11e9-9c76-01322c478851.png)

And the right cell:

![image](https://user-images.githubusercontent.com/5635170/50383011-898b7500-0710-11e9-9b47-2bf33369caf2.png)

Perhaps it's related to #291, but it's a different symptom though.

**Comment by danfickle** [comment] 2018-12-24 05:23
Hi @ralleman,

Thanks for the extra information. I was able to reproduce the problem and push a fix. It turns out the problem wasn't the borders themselves, but the background coverage when using collapsed borders.

It is now using the correct background coverage, so I'll close this issue. Thank you for reporting it.

**Closed as completed by danfickle** 2018-12-24 05:23 UTC
Labels: has passing test
