### ISSUE TITLE
How to set the size according to the ratio

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#189] opened 2018-03-29 08:56 UTC
DIV to PDF
I need to convert a div to a PDF, but the scale ratio is not correct. How do I scale the PDF?

I use @page, but just crop PDF, I want to show the full div

please help me

**Comment by danfickle** [comment] 2018-04-05 03:42
Hi @mapleLeat 

You can use the below code, although note that it relies on (mostly stable) internal APIs:
````java
	// An internal number, should stay the same.
	private static final int PDF_DOTS_PER_PIXEL = 20;
	
	public static void main(String... args) throws Exception {
		PdfRendererBuilder builder = new PdfRendererBuilder();
		
		// Note: We set a huge page size so it can auto-size the div without constraints.
		// Note: We must set a width on the div, otherwise it will be the width of the page.
		String html = "<html><head><style>@page { size: 10000px 10000px; } @page { margin: 0; } "
				+ "body { margin: 0; } div { width: 500px; }</style></head><body>"
				+ "<div>This is an auto-sized div<br/>This is a new line.</div>"
				+ "</body></html>";
		
		builder.withHtmlContent(html, /* Base url */ null);
		PdfBoxRenderer renderer = builder.buildPdfRenderer();
		renderer.layout();
		
		// The root box is <html>, the first child is <body>, then <div>.
		Box box = renderer.getRootBox().getChild(0).getChild(0);
		
		// Optional: Print box size to console.
		System.out.println("Box size = " + (box.getWidth() / PDF_DOTS_PER_PIXEL) + "x" + (box.getHeight() / PDF_DOTS_PER_PIXEL));
		System.out.println("Box element = " + box.getElement().getTagName());
		
		// Replace the original page size with the size of the <div> box.
		// Note the +1 to make sure it fits, could also try Math.ceil
		html = html.replace("@page { size: 10000px 10000px; }",
		        "@page { size: " + (Math.round(box.getWidth() / PDF_DOTS_PER_PIXEL) + 1) + "px "
		        + (Math.round(box.getHeight() / PDF_DOTS_PER_PIXEL) + 1) + "px; }");
		
		// Now output the new html.
		try (FileOutputStream fos = new FileOutputStream("/Users/me/Documents/pdf-issues/output/mytest-189.pdf")) {
			PdfRendererBuilder builder2 = new PdfRendererBuilder();
			builder2.withHtmlContent(html, null);
			builder2.toStream(fos);
			builder2.run();
		}
	}



````

**Comment by mapleLeat** [comment] 2018-04-12 06:55
@danfickle 
thanks your reply
I tried your method,But not the effect I want.
sorry,My English is translated by Google,May cause you to understand misery

example:
div{width:500px;height:300px;}
to the pdf size : 132.6mm x 79.6mm
I want to scale it according to proportion
(132.6mm x 79.6mm)  / 2    to   (66.3mm x 39.8)

I tried setting @page size
But the pdf automatically cuts pages

I hope you can understand what I say and help me, Thanks

**Comment by danfickle** [comment] 2018-04-16 07:01
I think maybe you want to scale the ```div``` to the page size, rather than the other way around? Maybe something like the below code, which scales the div to A4.

````java
	// An internal number, should stay the same.
	private static final int PDF_DOTS_PER_PIXEL = 20;
	
	private static final int A4_PIXEL_WIDTH = 793;
	private static final int A4_PIXEL_HEIGHT = 1122;
	
	private static final float PDF_POINT_WIDTH_A4 = 595f;
	private static final float PDF_POINT_HEIGHT_A4 = 841.88f;
	
	public static void main(String... args) throws Exception {
		PdfRendererBuilder builder = new PdfRendererBuilder();
		
		// First we create a document with too many lines to fit on page.
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < 100; i++) {
			sb.append("This is a div<br/>This is a new line.<br/>");
		}
		sb.append("LAST LINE");
		
		// Note: We set a huge page height so it can auto-size the div without constraints.
		String html = "<html><head><style>@page { size: " + A4_PIXEL_WIDTH + "px 10000px; } @page { margin: 0; } "
				+ "body { margin: 0; } div { font-size: 30px; } div { transform: none; transform-origin: left top; padding: 5px; }</style></head><body>"
				+ "<div>" + sb.toString() + "</div>"
				+ "</body></html>";
		
		builder.withHtmlContent(html, /* Base url */ null);
		PdfBoxRenderer renderer = builder.buildPdfRenderer();
		renderer.layout();
		
		// The root box is <html>, the first child is <body>, then <div>.
		Box box = renderer.getRootBox().getChild(0).getChild(0);
		
		renderer.getPdfDocument().close();
		renderer.close();

		float w = box.getWidth() / PDF_DOTS_PER_PIXEL;
		float h = box.getHeight() / PDF_DOTS_PER_PIXEL;

		// Figure out the scale factor.
		float scaleW = A4_PIXEL_WIDTH / w;
		float scaleH = A4_PIXEL_HEIGHT / h;
		float scale = Math.min(scaleW, scaleH);

		// Replace the original transform with the scale.
		html = html.replace("transform: none", String.format("transform: scale(%.3f)", scale));

		System.out.println("html:\n" + html);
		
		// Now output the new html.
		try (FileOutputStream fos = new FileOutputStream("/Users/me/Documents/pdf-issues/output/mytest-189.pdf")) {
			
			PdfRendererBuilder builder2 = new PdfRendererBuilder();
			builder2.withHtmlContent(html, /* Base uri. */ null);

			PdfBoxRenderer renderer2 = builder2.buildPdfRenderer();
			renderer2.createPDFWithoutClosing();

			PDDocument doc = renderer2.getPdfDocument();
			renderer2.close();

			// PDF page origin is bottom left, so we set a media box and crop box that takes the
			// the top A4 height of the page.
			PDRectangle mediaBox = doc.getPage(0).getMediaBox();
			doc.getPage(0).setCropBox(new PDRectangle(0f, mediaBox.getHeight() - PDF_POINT_HEIGHT_A4, PDF_POINT_WIDTH_A4, PDF_POINT_HEIGHT_A4));
			doc.getPage(0).setMediaBox(new PDRectangle(0f, mediaBox.getHeight() - PDF_POINT_HEIGHT_A4, PDF_POINT_WIDTH_A4, PDF_POINT_HEIGHT_A4));

			doc.save(fos);
			
			doc.close();
		}
	}
````

**Comment by mapleLeat** [comment] 2018-04-16 08:55
@danfickle 
sorry, I may not understand your code
I try to use `transform: scale,` the result still can not
This is my html string:
https://github.com/mapleLeat/maple/blob/master/testHtml

The converted pdf size is 264.6x211.7mm

Because of demand issues, I want to keep the div size constant, 1000 x 800 px
But I hope the converted PDF size is 132.3x105.8mm, Equal to half the original size

I tried to change the size of @page to 500x400, But the converted pdf is automatically cropped and paginated
```
@page {
	size: 1000px 800px ;
}
```

I don't understand the above code. Can you use my html as an example?
I'm sorry to waste your time

**Comment by danfickle** [comment] 2018-04-18 06:08
@mapleLeat 
A transform scale is the right approach. The problem is that the box collector and paginator is not transform aware (yet). So it is very hard to use successfully. If you know the size of the div, why not size it according to your page size? Could you outline what you are trying to do and I can maybe suggest an alternative?

**Comment by mapleLeat** [comment] 2018-04-18 06:28
@danfickle 
thank you for your help

I'm working on an online business card making project, In order to facilitate customer design, the page needs a larger div to display the business card, However, when the server generates a pdf, it must be scaled to a specified millimeter according to the div's scale.

When the size of the business card is 92x56
The size of the div should be magnified 7 times: width:644px,height:392px  (92x7=664,  56x7=392)
The converted pdf size should be 92mmx56mm
This size pdf can be printed

**Comment by danfickle** [comment] 2021-01-03 13:07
Transforms should now work correctly so closing for now.

**Closed as completed by danfickle** 2021-01-03 13:07 UTC

**Comment by markusher** [comment] 2022-04-04 12:08
@danfickle I am seeing some weird behaviour when it comes to scale transform and pagination, should that be working as intended now?
