### ISSUE TITLE
Form field names incorrect in resulting PDF

### ISSUE THREAD

**Issue by scoldwell** [danfickle/openhtmltopdf#42] opened 2016-10-18 22:57 UTC
the PDField partial name is being set to an internally generated name like "OpenHTMLCtrl1" and only the mapping name is being set to the name in the HTML.  This causes lookup from PDAcroForm.getField(String) to fail when looking up by the name in the HTML because the mapping name is not used in that lookup.

**Comment by danfickle** [comment] 2016-10-19 02:19
I didn't think of that use. The problem is that non ascii characters are only allowed in the mapping name. I suspose we could use the name if it is valid and warn and revert to a slugified name, if not. What do you think?

**Comment by scoldwell** [comment] 2016-10-19 02:30
I think that sounds reasonable

**Comment by danfickle** [comment] 2016-10-22 12:18
It turns out the restriction on non-ascii characters was lifted in Acrobat 6.0 so that's alright. I've done the basic implementation and will test further tomorrow. It's important to point out that in PDFs fields can be terminal or non-terminal only, not both. So this would fail because `parent` is being used as both:

``` html
<input type="text" name="parent"/>
<input type="text" name="parent.child"/>
```

**Comment by danfickle** [comment] 2016-10-23 04:37
Also, names must now be unique for each control (except radio button groups). So this would produce incorrect output:

``` html
<input type="checkbox" name="gender" value="male"/>
<input type="checkbox" name="gender" value="female"/>
<input type="checkbox" name="gender" value="other"/>
```

**Comment by danfickle** [comment] 2016-10-30 03:10
I think this is fixed so closing for now. Feel free to reopen if you have any further problems.

**Closed as completed by danfickle** 2016-10-30 03:10 UTC
