### ISSUE TITLE
Improve PdfRendererBuilder / PdfBoxRenderer for reuse 

### ISSUE THREAD

**Issue by ieugen** [danfickle/openhtmltopdf#355] opened 2019-05-27 16:08 UTC
Hello,

We are building an service to render some pdf's on request using openhtmltopdf. 
I'm constructing a `PdfRendererBuilder` to render the PDF. 

The builder is configured with some reusable parts - that don't change between runs: 
- fonts cache
- bidi splitter
- svg drawer, etc

And also some parts that change:
- the HTML content
- the output stream where the PDF is generated ?!

As it is built right now, there is no easy way to build a reusable `PdfBoxRenderer` - or at least there is no easy documented way on how to do it. 

How can we build a reusable `PdfBoxRenderer` or `PdfRendererBuilder` that is thread safe and can be re-used by changing the parts that change.

What happens if the code is called in a multi threaded environment ?

Thanks,

I'm using Spring to build the dependency graph and inject the `PdfRendererBuilder` 
```
@Slf4j
@FieldDefaults(level = AccessLevel.PRIVATE)
public class OpenHtmlToPdfRenderer {
  @Autowired PdfRendererBuilder builder;
  @Autowired OpenHtmlToPdfProperties config;

  public void run(String html, Path outputPath) {
    File output = outputPath.toFile();
    try (OutputStream os = new FileOutputStream(output)) {
      builder.withHtmlContent(html, config.getBaseUri());
      builder.toStream(os);
      builder.run();
    } catch (Exception e) {
      log.error("Error while generating PDF file: ", e);
    }
  }
}
```

The builder itself is setup like this:
```
@Slf4j
@FieldDefaults(level = AccessLevel.PRIVATE)
@Configuration
public class OpenHtmlToPdfConfiguration {

  @Bean
  public OkHttpClient okHttpClient() {
    return new OkHttpClient();
  }

  @Bean
  public FSStreamFactory fsStreamFactory(OkHttpClient client) {
    return new OkHttpStreamFactory(client);
  }

  @Bean
  public XRLogger xrLogger() {
    return new Slf4jLogger();
  }

  @Bean
  public BidiReorderer bidiReorderer() {
    return new ICUBidiReorderer();
  }

  @Bean
  public BidiSplitterFactory bidiSplitterFactory() {
    return new ICUBidiSplitter.ICUBidiSplitterFactory();
  }

  @Bean
  public SVGDrawer svgDrawer() {
    return new BatikSVGDrawer();
  }

  @Bean
  public MathMLDrawer mathMLDrawer() {
    return new MathMLDrawer();
  }

  @Bean
  public FSCacheEx<String, FSCacheValue> fsCacheEx() {
    return new FSDefaultCacheStore();
  }

  @Bean
  @ConfigurationProperties(prefix = "openhtmltopdf")
  public OpenHtmlToPdfProperties openHtmlToPdfProperties() {
    return new OpenHtmlToPdfProperties();
  }

  @Bean
  @Autowired
  public PdfRendererBuilder pdfRenderer(
      FSStreamFactory fsStreamFactory,
      FSCacheEx<String, FSCacheValue> fsCacheEx,
      OpenHtmlToPdfProperties config)
      throws IOException {

    XRLog.setLoggingEnabled(true);
    XRLog.setLoggerImpl(xrLogger());

    PdfRendererBuilder builder = new PdfRendererBuilder();
    builder.useFastMode();
    builder.useUnicodeBidiSplitter(bidiSplitterFactory());
    builder.useUnicodeBidiReorderer(bidiReorderer());
    builder.defaultTextDirection(BaseRendererBuilder.TextDirection.LTR); // OR RTL
    // configure http streaming
    builder.useHttpStreamImplementation(fsStreamFactory);
    // configure SVG and MathML
    builder.useSVGDrawer(svgDrawer());
    builder.useMathMLDrawer(mathMLDrawer());
    builder.useCacheStore(PdfRendererBuilder.CacheStore.PDF_FONT_METRICS, fsCacheEx);

    Path fonts = Path.of(config.getFontsDir());
    log.info("Loading fonts from {}", fonts.toAbsolutePath().toString());
    FileVisitor<Path> fileProcessor = new FontFileProcessor(builder);
    Files.walkFileTree(fonts, fileProcessor);

    return builder;
  }
}
```

**Comment by danfickle** [comment] 2019-05-31 05:31
You could theoretically reuse the builder in a single thread (it’s not thread safe) but it is very light weight compared to the process of turning HTML into a PDF, so I’d just create it from scratch each time.

**Comment by ieugen** [comment] 2019-06-05 01:08
Thanks. I don't have a lot of alternatives right now but the idea is that rebuilding the builder has some issues: 
- it's not supposed to work like that (rebuild the builder !? doesn't sound right, right ? ;) )
- fonts are processed every time - so the cache is not used in this case IMO

The above setup fails to render a PDF multiple times. It complains about not closing the document.

**Comment by danfickle** [comment] 2019-06-11 11:57
From memory, I think the font metrics cache uses font family/weight/style to match. So if you create a list of font files with those attributes on first run and use that list to pass to the builder the cache should hopefully work. If it doesn’t please let me know.

Note that the cache only avoids loading fallback fonts if they are not actually needed.

**Comment by rototor** [comment] 2019-06-11 15:19
@ieugen Sorry, but the builder is *not* supposed to be use for more than one rendering run by design. It is fully state full (i.e. it stores the document etc. in its internal state). A builder is by design just there to allow you to configure all that different options something can have. There are builders which try hard to be reuseable and threadsafe, this one does not. I also would never inject/autowire a builder ... they are "temp" objects by design.

Regarding multithreading: Did you determine that the builder is your real bottleneck in your application? Or are you just guessing?

I've got a project which generates tons of PDFs in a multithreaded environment using PDFBox. I get some random PDFBox failures from time to time; When retrying to generate the PDF it usually works. This seems like some funny PDFBox multithread race to me, but as the retrying is done automatically in my software and it is not reproduceable, I did not investigate future. (Also the exceptions I get are not helpful...)

=> I would suggest you try to get your service running stable under load with multiply requests/PDFs generated in parallel first. I would not be that sure (at the moment) that this will really work fine all the time. But if you can trigger those PDFBox bugs reliable you might be able to point to a fix for that. 

Optimizing should come later. And I don't think that the builder is something which you can/should use for optimization.

**Comment by ieugen** [comment] 2019-06-12 06:36
Thank you both for your feedback. I appreciate it. I'm just guessing at this time as I did not investigate thoroughly.

Regarding the builder, I believe that the PDF document should be pulled out of the state and this should make it reusable IMO. 

There are configurations that change from rendering to rendering and some that don't change.
I believe the builder should manage the ones that don't change (fonts cache, svg renderer, etc.) . 
The rest of the options that change: the document, paths to save, etc should be kept out and passes as parameters or like a render command. 

That is how I see things anyway. 

Regards,
Eugen

**Comment by danfickle** [comment] 2019-11-01 10:28
Closed as very-low-priority. Thanks anyway.

**Closed as completed by danfickle** 2019-11-01 10:28 UTC
